# Version
version: @project.version@
# Server
server:
  port: 8080
  servlet:
    context-path: /wallet/v1
    session:
      timeout: 3600s
      cookie:
        domain: localhost
        path: /
        name: SESSION_ID
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    min-spare-threads: 10
# MySQL
spring:
  datasource:
    url: jdbc:mysql://47.244.230.227:3306/goldbox?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
    password: yX7+qA#f@9cgv~br
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 3
    host: 47.244.230.227
    port: 6379
    password: xyxRedis6379
    timeout: 10000ms
    jedis:
      pool:
        max-active: 200
        max-idle: 50
        max-wait: 10000ms
        min-idle: 8
  quartz:
    properties:
      org.quartz.threadPool.threadCount: 15

# Log
logging:
  path: ./log
  file: log/wallet.log
  file.max-size: 10MB
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    com.my.demo.wallet: debug
    org.springframework: warn
    org.spring.springboot.dao: debug


ethereum:
  rpcClient:
    # token4dev:12ab05a5e3b24d75b4c43a57c5683169
    # token:1ee437e1fcd44e6b9df11958290ba4c6
    url: https://ropsten.infura.io/v3/12ab05a5e3b24d75b4c43a57c5683169
#    url: https://mainnet.infura.io/v3/12ab05a5e3b24d75b4c43a57c5683169
#    url: http://192.168.1.200:8545
#    url: http://localhost:8545
#    url: http://47.75.177.252:8545
  wallet:
    keystore:
#      path: /Users/yimcarson/Workspace/aipay/aipay-wallet/keystore
#      path: /data/keystore
      path: ./keystore
